# Generated by Django 5.1.2 on 2024-12-05 01:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compatibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilArrendador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('pref_no_fumador', models.IntegerField(choices=[(0, 'Seleccione una opción'), (3, 'No permitido'), (2, 'Prefiero que no'), (1, 'Me es indiferente')], default=1)),
                ('pref_no_bebedor', models.IntegerField(choices=[(0, 'Seleccione una opción'), (3, 'No permitido'), (2, 'Prefiero que no'), (1, 'Me es indiferente')], default=1)),
                ('pref_no_mascotas', models.IntegerField(choices=[(0, 'Seleccione una opción'), (3, 'No permitido'), (2, 'Prefiero que no'), (1, 'Me es indiferente')], default=1)),
                ('pref_estudiante_verificado', models.IntegerField(choices=[(0, 'Seleccione una opción'), (3, 'Es obligatorio'), (2, 'Es preferible'), (1, 'No es necesario')], default=1)),
                ('pref_nivel_ruido', models.IntegerField(choices=[(0, 'Seleccione una opción'), (3, 'Debe ser muy silencioso'), (2, 'Ruido moderado aceptable'), (1, 'Sin restricciones de ruido')], default=1)),
                ('horario_visitas', models.CharField(blank=True, max_length=200)),
                ('reglas_casa', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilArrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('universidad', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('documento_estudiante', models.FileField(blank=True, help_text='Certificado de alumno regular o matrícula', upload_to='documentos_estudiante/')),
                ('bebedor', models.CharField(choices=[('', 'Seleccione una opción'), ('si', 'Sí'), ('casual', 'Casual'), ('no', 'No')], max_length=10)),
                ('fumador', models.CharField(choices=[('', 'Seleccione una opción'), ('si', 'Sí'), ('ocasional', 'Ocasional'), ('no', 'No')], max_length=10)),
                ('mascota', models.CharField(choices=[('', 'Seleccione una opción'), ('tengo', 'Ya tengo'), ('planeo', 'Planeo tener'), ('no', 'No')], max_length=10)),
                ('tipo_mascota', models.CharField(blank=True, max_length=50)),
                ('nivel_ruido', models.IntegerField(choices=[(0, 'Seleccione una opción'), (1, 'Muy silencioso'), (2, 'Normal'), (3, 'Ruidoso')], default=0)),
                ('horario_llegada', models.TimeField(blank=True, null=True)),
                ('presupuesto_max', models.CharField(blank=True, help_text='Presupuesto máximo con formato (ej: 250.000)', max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('telefono', models.CharField(help_text='Número de teléfono de contacto', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('Arrendador', 'Arrendador'), ('Arrendatario', 'Arrendatario')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
