# Generated by Django 5.1.2 on 2024-11-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilarrendador',
            name='pref_estudiante_verificado',
            field=models.IntegerField(choices=[(0, 'Seleccione una opción'), (3, 'Es obligatorio'), (2, 'Es preferible'), (1, 'No es necesario')], default=1),
        ),
        migrations.AlterField(
            model_name='perfilarrendador',
            name='pref_nivel_ruido',
            field=models.IntegerField(choices=[(0, 'Seleccione una opción'), (3, 'No permitido'), (2, 'Prefiero que no'), (1, 'Me es indiferente')], default=1),
        ),
        migrations.AlterField(
            model_name='perfilarrendador',
            name='pref_no_bebedor',
            field=models.IntegerField(choices=[(0, 'Seleccione una opción'), (3, 'No permitido'), (2, 'Prefiero que no'), (1, 'Me es indiferente')], default=1),
        ),
        migrations.AlterField(
            model_name='perfilarrendador',
            name='pref_no_fumador',
            field=models.IntegerField(choices=[(0, 'Seleccione una opción'), (3, 'No permitido'), (2, 'Prefiero que no'), (1, 'Me es indiferente')], default=1),
        ),
        migrations.AlterField(
            model_name='perfilarrendador',
            name='pref_no_mascotas',
            field=models.IntegerField(choices=[(0, 'Seleccione una opción'), (3, 'No permitido'), (2, 'Prefiero que no'), (1, 'Me es indiferente')], default=1),
        ),
        migrations.AlterField(
            model_name='perfilarrendatario',
            name='bebedor',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('si', 'Sí'), ('casual', 'Casual'), ('no', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilarrendatario',
            name='fumador',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('si', 'Sí'), ('ocasional', 'Ocasional'), ('no', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilarrendatario',
            name='mascota',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('tengo', 'Ya tengo'), ('planeo', 'Planeo tener'), ('no', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilarrendatario',
            name='nivel_ruido',
            field=models.IntegerField(choices=[(0, 'Seleccione una opción'), (1, 'Muy silencioso'), (2, 'Normal'), (3, 'Ruidoso')], default=0),
        ),
    ]
