# Generated by Django 5.1.2 on 2024-11-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_app', '0003_alter_perfilarrendador_pref_estudiante_verificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilarrendador',
            name='pref_nivel_ruido',
            field=models.IntegerField(choices=[(0, 'Seleccione una opción'), (3, 'Debe ser muy silencioso'), (2, 'Ruido moderado aceptable'), (1, 'Sin restricciones de ruido')], default=1),
        ),
    ]
