# Generated by Django 5.1.2 on 2024-11-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_app', '0004_alter_perfilarrendador_pref_nivel_ruido'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibilidad',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
