# Generated by Django 5.1.2 on 2024-12-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_app', '0004_usuario_fecha_nacimiento_usuario_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
