# Generated by Django 5.1.2 on 2024-12-10 01:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_app', '0005_usuario_email_verified_usuario_otp_code_and_more'),
        ('ArrendaU_publicaciones_app', '0005_publicacion_latitud_publicacion_longitud_reseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reseña', models.CharField(choices=[('ARRENDADOR_A_ARRENDATARIO', 'Arrendador a Arrendatario'), ('ARRENDATARIO_A_ARRENDADOR', 'Arrendatario a Arrendador')], max_length=50)),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_escritas', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ArrendaU_publicaciones_app.publicacion')),
                ('usuario_reseñado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
