# Generated by Django 5.1.2 on 2024-11-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_app', '0006_remove_compatibilidad_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compatibilidad',
            name='descripcion_compatibilidad',
        ),
    ]
