# Generated by Django 5.1.2 on 2024-11-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_app', '0007_remove_compatibilidad_descripcion_compatibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibilidad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
