# Generated by Django 5.1.2 on 2024-12-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_app', '0007_interaccion_resena_delete_reseña'),
        ('ArrendaU_publicaciones_app', '0006_publicacion_oculta_para_arrendatario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('autor', 'usuario_resenado', 'publicacion')},
        ),
    ]
