# Generated by Django 5.1.2 on 2024-12-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_app', '0008_alter_resena_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilarrendatario',
            name='documento_razon',
            field=models.CharField(blank=True, help_text='Razón del estado de verificación del documento', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfilarrendatario',
            name='documento_texto',
            field=models.TextField(blank=True, help_text='Texto extraído del documento estudiante', null=True),
        ),
        migrations.AddField(
            model_name='perfilarrendatario',
            name='documento_verificado',
            field=models.BooleanField(default=False, help_text='Indica si el documento ha sido verificado como válido'),
        ),
    ]
