# Generated by Django 5.1.2 on 2024-12-05 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_pagos', '0001_initial'),
        ('ArrendaU_publicaciones_app', '0002_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='pago',
            name='factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='publicacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='ArrendaU_publicaciones_app.publicacion'),
        ),
    ]
