# Generated by Django 5.1.2 on 2024-12-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_pagos', '0002_alter_pago_options_pago_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='detalles_transaccion',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
