# Generated by Django 5.1.2 on 2024-12-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_pagos', '0004_alter_pago_estado_alter_pago_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='publicacion_ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='publicacion_direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='publicacion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
