# Generated by Django 5.1.2 on 2024-11-17 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('region', models.CharField(choices=[('araucania', 'Araucanía'), ('biobio', 'Bío Bío'), ('los_lagos', 'Los Lagos'), ('metropolitana', 'Metropolitana'), ('valparaiso', 'Valparaíso'), ('ohiggins', "O'Higgins"), ('maule', 'Maule'), ('nuble', 'Ñuble'), ('los_rios', 'Los Ríos'), ('arica', 'Arica y Parinacota'), ('tarapaca', 'Tarapacá'), ('antofagasta', 'Antofagasta'), ('atacama', 'Atacama'), ('coquimbo', 'Coquimbo'), ('aysen', 'Aysén'), ('magallanes', 'Magallanes')], max_length=50)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('numero_contacto', models.CharField(max_length=20)),
                ('habitaciones_disponibles', models.IntegerField()),
                ('valor_alquiler', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ArrendaU_publicaciones_app.publicacion')),
            ],
        ),
    ]
