# Generated by Django 5.1.2 on 2024-12-05 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioCompatibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.CharField(max_length=500)),
                ('respuesta_esperada', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='ArrendaU_publicaciones_app.formulariocompatibilidad')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='ArrendaU_publicaciones_app.preguntaformulario')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('region', models.CharField(choices=[('arica', 'Arica y Parinacota'), ('tarapaca', 'Tarapacá'), ('antofagasta', 'Antofagasta'), ('atacama', 'Atacama'), ('coquimbo', 'Coquimbo'), ('valparaiso', 'Valparaíso'), ('metropolitana', 'Metropolitana'), ('ohiggins', "O'Higgins"), ('maule', 'Maule'), ('nuble', 'Ñuble'), ('biobio', 'Bío Bío'), ('araucania', 'Araucanía'), ('los_rios', 'Los Ríos'), ('los_lagos', 'Los Lagos'), ('aysen', 'Aysén'), ('magallanes', 'Magallanes')], max_length=50)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('numero_contacto', models.CharField(max_length=20)),
                ('habitaciones_disponibles', models.IntegerField()),
                ('valor_alquiler', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('vistas', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACEPTADO', 'Postulación Aceptada'), ('RECHAZADO', 'Postulación Rechazada')], max_length=20)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArrendaU_publicaciones_app.publicacion')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ArrendaU_publicaciones_app.publicacion')),
            ],
        ),
        migrations.AddField(
            model_name='formulariocompatibilidad',
            name='publicacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulario', to='ArrendaU_publicaciones_app.publicacion'),
        ),
        migrations.CreateModel(
            name='RespuestaArrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_arrendatarios', to='ArrendaU_publicaciones_app.formulariocompatibilidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_seleccionada', models.CharField(max_length=200)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArrendaU_publicaciones_app.preguntaformulario')),
                ('respuesta_arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='ArrendaU_publicaciones_app.respuestaarrendatario')),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardada_por', to='ArrendaU_publicaciones_app.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_guardadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_guardado'],
                'unique_together': {('usuario', 'publicacion')},
            },
        ),
    ]
