# Generated by Django 5.1.2 on 2024-11-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='region',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='valor_alquiler',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones_fotos/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='habitaciones_disponibles',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='numero_contacto',
            field=models.CharField(max_length=15),
        ),
    ]
