# Generated by Django 5.1.2 on 2024-11-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='preguntas_compatibilidad',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='respuestas_esperadas',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
