# Generated by Django 5.1.2 on 2024-12-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('PENDIENTE', 'Nueva Postulación'), ('ACEPTADO', 'Postulación Aceptada'), ('RECHAZADO', 'Postulación Rechazada')], max_length=20),
        ),
    ]
