# Generated by Django 5.1.2 on 2024-12-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0002_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='PENDIENTE_PAGO', max_length=20),
        ),
    ]
