# Generated by Django 5.1.2 on 2024-11-10 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0002_publicacion_ciudad_publicacion_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='fotos',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='valor_alquiler',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='FotoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='publicaciones_fotos/')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ArrendaU_publicaciones_app.publicacion')),
            ],
        ),
    ]
