# Generated by Django 5.1.2 on 2024-11-21 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0002_respuestaarrendatario_respuestapregunta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardada_por', to='ArrendaU_publicaciones_app.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_guardadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_guardado'],
                'unique_together': {('usuario', 'publicacion')},
            },
        ),
    ]
