# Generated by Django 5.1.2 on 2024-11-19 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0002_publicacion_preguntas_compatibilidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='preguntas_compatibilidad',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='respuestas_esperadas',
        ),
        migrations.CreateModel(
            name='FormularioCompatibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('publicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulario', to='ArrendaU_publicaciones_app.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.CharField(max_length=500)),
                ('respuesta_esperada', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='ArrendaU_publicaciones_app.formulariocompatibilidad')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='ArrendaU_publicaciones_app.preguntaformulario')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
