# Generated by Django 5.1.2 on 2024-11-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0003_publicacionguardada'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaarrendatario',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
    ]
