# Generated by Django 5.1.2 on 2024-11-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0003_remove_publicacion_fotos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
        migrations.DeleteModel(
            name='FotoPublicacion',
        ),
    ]
