# Generated by Django 5.1.2 on 2024-11-11 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0004_publicacion_fotos_delete_fotopublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='fotos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArrendaU_publicaciones_app.publicacion')),
            ],
        ),
    ]
