# Generated by Django 5.1.2 on 2024-11-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0004_respuestaarrendatario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
