# Generated by Django 5.1.2 on 2024-11-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0005_alter_publicacion_fotos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
