# Generated by Django 5.1.2 on 2024-12-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0005_publicacion_latitud_publicacion_longitud_reseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='oculta_para_arrendatario',
            field=models.BooleanField(default=False),
        ),
    ]
