# Generated by Django 5.1.2 on 2024-12-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0006_publicacion_oculta_para_arrendatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaarrendatario',
            name='oculta_para_arrendatario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='respuestaarrendatario',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('EXPULSADO', 'Expulsado')], default='PENDIENTE', max_length=20),
        ),
    ]
