# Generated by Django 5.1.2 on 2024-11-11 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0006_alter_publicacion_fotos_delete_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='fotos',
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ArrendaU_publicaciones_app.publicacion')),
            ],
        ),
    ]
