# Generated by Django 5.1.2 on 2024-11-22 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0007_postulacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postulacion',
        ),
    ]
