# Generated by Django 5.1.2 on 2024-12-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0007_respuestaarrendatario_oculta_para_arrendatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PUBLICADA', 'Publicada'), ('INACTIVA', 'Inactiva'), ('SIN_CUPOS', 'Sin Cupos')], default='BORRADOR', max_length=20),
        ),
    ]
