# Generated by Django 5.1.2 on 2024-11-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0008_alter_foto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='valor_alquiler',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
