# Generated by Django 5.1.2 on 2024-12-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0008_alter_publicacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PUBLICADA', 'Publicada'), ('INACTIVA', 'Inactiva')], default='BORRADOR', max_length=20),
        ),
    ]
