# Generated by Django 5.1.2 on 2024-11-16 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0009_alter_publicacion_valor_alquiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='formulario_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500)),
                ('opciones', models.JSONField()),
                ('respuesta_correcta', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulario', to='ArrendaU_publicaciones_app.publicacion')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('publicacion', 'orden')},
            },
        ),
    ]
