# Generated by Django 5.1.2 on 2024-11-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArrendaU_publicaciones_app', '0010_publicacion_formulario_activo_formulario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
